version: 2.1
jobs:
  build:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Build
          command: npm run build
      - run:
          name: Run tests
          command: npm run test
